[config]
schemaVersion = "0.0.1"

[package]
namespace = "RedstoneWizard08"
name = "ContentLibrary"
versionNumber = "0.1.0"
description = "A library for all of your Content Warning modding needs! (Also the successor to ContentSettings!)"
websiteUrl = "https://redstonewizard08.github.io/ConfigurableWarning"
containsNsfwContent = false

[package.dependencies]
RugbugRedfern-MyceliumNetworking = "1.0.14"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./output"

[[build.copy]]
source = "./ContentLibrary/bin/Release/netstandard2.1/RedstoneWizard08.ContentLibrary.dll"
target = "RedstoneWizard08.ContentLibrary.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = ["content-warning"]

[publish.categories]
content-warning = ["mods", "tools", "misc", "bepinex"]
