apiRules:
    # Exclude any class under any module named Plugin or MyPluginInfo
    - exclude:
          uidRegex: ^ConfigurableWarning\.Plugin$
          type: Class
    - exclude:
          uidRegex: ^ConfigurableWarning\.MyPluginInfo$
          type: Class
    - exclude:
          uidRegex: ^ConfigurableWarning\..*\.SettingPatches$
          type: Class
