name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
            dotnet tool update -g docfx
            dotnet tool restore
            python3 deps.py
            chmod +x build.sh
            ./build.sh

      - uses: actions/upload-artifact@v4
        name: Upload Artifacts
        with:
          if-no-files-found: error
          name: ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}.zip
          path: |
            **/bin/**/*.dll
            output/**/*.zip
